#!/bin/bash
#--------------------------
# SCRIPT SPEED GENERATOR 
# CANAL TELEGRAM: @srSPEEDiness
#--------------------------
clear
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
apt install git -y &>/dev/null 
apt install figlet boxes -y &>/dev/null
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"| lolcat
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["| lolcat
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["| lolcat
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"| lolcat
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo ""
echo -e "\033[1;37m $system                          $date"| lolcat
figlet ' SPEEDCELL PREMIUM ' | boxes -d stone -p a0v0 | lolcat
echo "SE VOCÊ NÃO PUDER SE DESTACAR PELO TALENTO, VENÇA PELO ESFORÇO."| lolcat
echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"| lolcat
echo ""
echo ""
echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"| lolcat
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"| lolcat
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"| lolcat
echo -e "\033[1;31m• \033[1;33mSOLICITE SUA KEY PELO TELEGRAM @srSPEEDiness\033[0m"| lolcat
echo -e "\033[1;31m \033[1;33m\033[0m"| lolcat
echo ""
echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"| lolcat
echo ""
echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "| lolcat; read _key_
if [[ -z $_key_ ]]; then
echo ""
echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
sleep 1
clear; exit
fi
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $_key_\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink install.speedcell.ga/$_key_/list > /dev/null 2>&1; verif_key
sleep 3s
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
sleep 3s
clear
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install figlet boxes -y &>/dev/null
instala_fun () {
echo -e "\033[1;33mINSTALANDO... \033[1;32mAGUARDE"| lolcat
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"| lolcat
echo -e " "
# ACTUALIZA REPOSITORIO
echo -e "\033[1;33m ATUALIZANDO REPOSITÓRIO... \033[1;32mAGUARDE"| lolcat
apt-get update -y > /dev/null 2>&1
apt-get upgrade -y > /dev/null 2>&1
apt-get install curl -y > /dev/null 2>&1
apt-get install apache2 -y > /dev/null 2>&1
sed -i "s;Listen 81;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
mkdir /var/www/html/script > /dev/null 2>&1
mkdir /var/www/html/_S_script > /dev/null 2>&1
touch /var/www/html/script/index.html
touch /var/www/html/_S_script/index.html
echo -e " "
# INSTALL ARQUIVOS
echo -e "\033[1;33m INSTALANDO ARQUIVOS... \033[1;32mAGUARDE"| lolcat
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/Plus -O /var/www/html/Plus > /dev/null 2>&1
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/list -O /home/list > /dev/null 2>&1
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/versao -O /home/versao > /dev/null 2>&1 && cat /home/versao >/var/www/html/script/versao
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/keyssh -O /bin/keyssh > /dev/null 2>&1
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/stunnel.pem -O /var/www/html/script/stunnel.pem > /dev/null 2>&1
wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/otimizar -O /bin/otimizar > /dev/null 2>&1
echo -e " "
# PERMISOS ARQUIVOS
echo -e "\033[1;33m PERMITINDO ARQUIVOS... \033[1;32mAGUARDE"| lolcat
chmod +x  /var/www/html/Plus > /dev/null 2>&1
chmod +x  /home/list > /dev/null 2>&1
chmod +x  /home/versao > /dev/null 2>&1
chmod +x  /bin/keyssh > /dev/null 2>&1
chmod +x  /bin/otimizar > /dev/null 2>&1
# HISTORY
cat /dev/null > ~/.bash_history && history -c
echo -e " "
# MONTANDO O SEU LINK-IP
echo -e "\033[1;33m MONTANDO O SEU LINK-IP... \033[1;32mAGUARDE"| lolcat
apt-get install curl -y > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
if [[ -e "/var/www/html/Plus" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /var/www/html/Plus > /dev/null 2>&1
fi
apt-get install curl -y > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
if [[ -e "/home/list" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /home/list > /dev/null 2>&1
fi
sleep 6s
echo -e " "
# DONWLOAD SERVER
#echo -e "\033[1;33m DONWLOAD SERVER... \033[1;32mAGUARDE"
#apt-get install zip -y > /dev/null 2>&1
#apt-get install unzip -y > /dev/null 2>&1
#apt-get install curl -y > /dev/null 2>&1
#[[ ! -d /var/www/html/_S_script ]] && mkdir /var/www/html/_S_script
#cd /var/www/html/_S_script
#wget https://github.com/srSPEEDiness/keyssh-gerador/raw/main/install/sshplus-v32.zip > /dev/null 2>&1
#unzip sshplus-v32.zip > /dev/null 2>&1
#rm -rf sshplus-v32.zip
#cd
# HISTORY
cat /dev/null > ~/.bash_history && history -c
echo -e " "
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"| lolcat
echo -e "\033[1;37m Perfeito, Use o Comando \033[1;31mkeyssh \033[1;37m
 para Gerenciar as Suas Keys e
 Atualizar a Base do servidor"| lolcat
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"| lolcat
rm -rf $HOME/instala_server > /dev/null 2>&1
}

clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"| lolcat
echo -e "\033[1;31mINSTALADOR SPEEDCELL GENERATOR \033[0m"| lolcat
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"| lolcat
echo -ne "\033[0m"
instala_fun
